name: Build and Push LaTeX PDF to Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: main.pdf

      - name: Commit and push PDF to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add main.pdf
          git commit -m "Auto-compile PDF from LaTeX [skip ci]" || echo "No changes to commit"
          git push origin main
